stages:
  - build
  - release

variables:
  EXECUTABLE_NAME: fractal_rndr
  INSTANCE: gitlab.com

# Linux build
build-linux:
  stage: build
  image: rust:latest
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --target x86_64-unknown-linux-gnu --release
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/${EXECUTABLE_NAME}
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]\.[0-9]\.[0-9](-rc.+)?/'

# Windows build
build-windows:
  stage: build
  image: rust:latest
  script:
    - rustup target add x86_64-pc-windows-gnu
    - apt-get update && apt-get install -y mingw-w64
    - cargo build --target x86_64-pc-windows-gnu --release
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/${EXECUTABLE_NAME}.exe
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]\.[0-9]\.[0-9](-rc.+)?/'

# Release job
release:
  stage: release
  image: dwdraju/alpine-curl-jq
  needs:
    - job: build-linux
      artifacts: true
    - job: build-windows
      artifacts: true
  script:
    - |
      # Get the release ID using the GitLab API
      RELEASE_ID=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "https://$INSTANCE/api/v4/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG_NAME" | jq -r '.id')
      # Attach the Linux binary to the release
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --header "Content-Disposition: attachment; filename=${EXECUTABLE_NAME}-linux" --upload-file "target/x86_64-unknown-linux-gnu/release/${EXECUTABLE_NAME}" "https://$INSTANCE/api/v4/projects/$CI_PROJECT_ID/releases/$RELEASE_ID/uploads?url=true"
      # Attach the Windows binary to the release
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --header "Content-Disposition: attachment; filename=${EXECUTABLE_NAME}-windows.exe" --upload-file "target/x86_64-pc-windows-gnu/release/${EXECUTABLE_NAME}.exe" "https://$INSTANCE/api/v4/projects/$CI_PROJECT_ID/releases/$RELEASE_ID/uploads?url=true"
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]\.[0-9]\.[0-9](-rc.+)?/'
