[package]
name = "fractal_rndr"
version = "0.2.6"
description = "A fractal renderer that features several coloring modes, anti-aliasing and a gui."
keywords = ["fractal", "renderer", "anti-aliasing"]
homepage = "https://gitlab.com/valflrt/fractal_rndr"
authors = ["valflrt"]
edition = "2021"
license = "MIT"

[dependencies]
eframe = "0.33.0"
egui_extras = { version = "0.33.0", default-features = false, features = ["image"] }
fastrand = "2.3.0"
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg"] }
rayon = "1.11.0"
rfd = "0.17.2"
ron = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }
valargs = "0.1.9"
wide = "1.1.1"

[features]
default = []
force_f32 = []
